src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $com_date = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $com_commentaire = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $com_uti = null;

    #[ORM\OneToMany(mappedBy: 'pan_com', targetEntity: Panier::class, cascade: ['persist'])]
    private Collection $paniers;

    #[ORM\OneToMany(mappedBy: 'bon_com', targetEntity: BonLivraison::class)]
    private Collection $bonLivraisons;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $com_adresse_livraison = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $com_adresse_facturation = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Transporteur $com_transporteur = null;

    #[ORM\Column]
    private ?bool $com_isPaid = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $com_moyen_paiement = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $com_stripe_session_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $com_paypal_id = null;

    #[ORM\Column(nullable: true)]
    private ?int $com_facture_id = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $com_facture_total_ht = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $com_facture_tva = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $com_facture_total_ttc = null;

    public function __construct()
    {
        $this->com_date = new \DateTimeImmutable();
        $this->paniers = new ArrayCollection();
        $this->bonLivraisons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComDate(): ?\DateTimeImmutable
    {
        return $this->com_date;
    }

    // public function setComDate(\DateTimeImmutable $com_date): static
    // {
    //     $this->com_date = $com_date;

    //     return $this;
    // }
    
    #[ORM\PrePersist]
    public function setComDate(): static
    {
        $this->com_date =  new \DateTimeImmutable();

        return $this;
    }

    public function getComCommentaire(): ?string
    {
        return $this->com_commentaire;
    }

    public function setComCommentaire(?string $com_commentaire): static
    {
        $this->com_commentaire = $com_commentaire;

        return $this;
    }

    public function getComUti(): ?Utilisateur
    {
        return $this->com_uti;
    }

    public function setComUti(?Utilisateur $com_uti): static
    {
        $this->com_uti = $com_uti;

        return $this;
    }

    /**
     * @return Collection<int, Panier>
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(Panier $panier): static
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers->add($panier);
            $panier->setPanCom($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): static
    {
        if ($this->paniers->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getPanCom() === $this) {
                $panier->setPanCom(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, BonLivraison>
     */
    public function getBonLivraisons(): Collection
    {
        return $this->bonLivraisons;
    }

    public function addBonLivraison(BonLivraison $bonLivraison): static
    {
        if (!$this->bonLivraisons->contains($bonLivraison)) {
            $this->bonLivraisons->add($bonLivraison);
            $bonLivraison->setBonCom($this);
        }

        return $this;
    }

    public function removeBonLivraison(BonLivraison $bonLivraison): static
    {
        if ($this->bonLivraisons->removeElement($bonLivraison)) {
            // set the owning side to null (unless already changed)
            if ($bonLivraison->getBonCom() === $this) {
                $bonLivraison->setBonCom(null);
            }
        }

        return $this;
    }

    public function getComAdresseLivraison(): ?string
    {
        return $this->com_adresse_livraison;
    }

    public function setComAdresseLivraison(string $com_adresse_livraison): static
    {
        $this->com_adresse_livraison = $com_adresse_livraison;

        return $this;
    }

    public function getComAdresseFacturation(): ?string
    {
        return $this->com_adresse_facturation;
    }

    public function setComAdresseFacturation(string $com_adresse_facturation): static
    {
        $this->com_adresse_facturation = $com_adresse_facturation;

        return $this;
    }

    public function getComTransporteur(): ?Transporteur
    {
        return $this->com_transporteur;
    }

    public function setComTransporteur(?Transporteur $com_transporteur): static
    {
        $this->com_transporteur = $com_transporteur;

        return $this;
    }

    public function isComIsPaid(): ?bool
    {
        return $this->com_isPaid;
    }

    public function setComIsPaid(bool $com_isPaid): static
    {
        $this->com_isPaid = $com_isPaid;

        return $this;
    }

    public function getComMoyenPaiement(): ?string
    {
        return $this->com_moyen_paiement;
    }

    public function setComMoyenPaiement(?string $com_moyen_paiement): static
    {
        $this->com_moyen_paiement = $com_moyen_paiement;

        return $this;
    }

    public function getComStripeSessionId(): ?string
    {
        return $this->com_stripe_session_id;
    }

    public function setComStripeSessionId(?string $com_stripe_session_id): static
    {
        $this->com_stripe_session_id = $com_stripe_session_id;

        return $this;
    }

    public function getComPaypalId(): ?string
    {
        return $this->com_paypal_id;
    }

    public function setComPaypalId(?string $com_paypal_id): static
    {
        $this->com_paypal_id = $com_paypal_id;

        return $this;
    }

    public function getComFactureId(): ?int
    {
        return $this->com_facture_id;
    }

    public function setComFactureId(?int $com_facture_id): static
    {
        $this->com_facture_id = $com_facture_id;

        return $this;
    }

    public function getComFactureTotalHt(): ?string
    {
        return $this->com_facture_total_ht;
    }

    public function setComFactureTotalHt(?string $com_facture_total_ht): static
    {
        $this->com_facture_total_ht = $com_facture_total_ht;

        return $this;
    }

    public function getComFactureTva(): ?string
    {
        return $this->com_facture_tva;
    }

    public function setComFactureTva(?string $com_facture_tva): static
    {
        $this->com_facture_tva = $com_facture_tva;

        return $this;
    }

    public function getComFactureTotalTtc(): ?string
    {
        return $this->com_facture_total_ttc;
    }

    public function setComFactureTotalTtc(?string $com_facture_total_ttc): static
    {
        $this->com_facture_total_ttc = $com_facture_total_ttc;

        return $this;
    }

}

src/Controller/CommandeCrudController.php
<?php

namespace App\Controller;

use App\Entity\Panier;
use App\Entity\Commande;
use App\Form\Commande1Type;
use App\Repository\AdresseRepository;
use App\Repository\PanierRepository;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/commande/crud')]

class CommandeCrudController extends AbstractController
{
   // #[IsGranted('ROLE_ADMIN')]
    #[Route('/', name: 'app_commande_crud_index', methods: ['GET'])]
    public function index(CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande_crud/index.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }

    #[Route('/mesCommande', name: 'app_commande_mon_index', methods: ['GET'])]
    public function monIndex(CommandeRepository $commandeRepository,PanierRepository $panierRepository): Response
    {
        // $x = $commandeRepository->findBy(['com_uti' => $this->getUser()]);
        //  $y = $commandeRepository->myCommandeByCom();
        //  dd($y);
       // dd($x[2]->getId());
        return $this->render('commande_crud/my_commande.html.twig', [
            'commandes' => $commandeRepository->findBy(['com_uti' => $this->getUser()]),
            //'myCommandes' => $commandeRepository->myCommande(),
            //'paniers' => $panierRepository->findBy(['pan_com' => ])
        ]);
    }

    #[Route('/mesCommande/{id}', name: 'app_my_commande_crud_show', methods: ['GET'])]
    public function showDetailCommande(Commande $commande, CommandeRepository $commandeRepository, AdresseRepository $adresseRepository, $id): Response
    {
        $comId = $commandeRepository->findOneBy(['com_facture_id' => $id])->getId();
        $utiId = $commandeRepository->findOneBy(['com_facture_id' => $id])->getComUti()->getId();
        $facId = $commandeRepository->findOneBy(['com_facture_id' => $id])->getComFactureId();
        $comDate = $commandeRepository->findOneBy(['com_facture_id' => $id])->getComDate();
        $facDate = $commandeRepository->findOneBy(['com_facture_id' => $id])->getComDate();
          // $y = $commandeRepository->myCommandeByCom($id);
        //    $y = $commandeRepository->totalPrixCom($id);
          // dd($commandeRepository->myCommandeByCom($id));
        // $t = $commandeRepository->myCommande();
        //$x = $adresseRepository->findBy(['adr_uti' => $utiId]);
        //dd($adresseRepository->findBy(['adr_uti' => $utiId]));
        // dd($commandeRepository->myCommandeByCom($id)[0]['c_adLiv']);
        return $this->render('commande_crud/facture.html.twig', [
            //'commande' => $commande,
            'comId' => $comId,
            'utiId' => $utiId,
           // 'nom' => $commandeRepository->myCommandeByCom($id)[0]['nom'],
            //'prenom' => $commandeRepository->myCommandeByCom($id)[0]['prenom'],
            'adresse' => $commandeRepository->myCommandeByCom($id)[0]['c_adLiv'],
            'adresseFac' => $commandeRepository->myCommandeByCom($id)[0]['c_adFac'],
            'tel' => $commandeRepository->myCommandeByCom($id)[0]['user_tel'],
            'email' => $commandeRepository->myCommandeByCom($id)[0]['user_email'],
            'adresse' => $commandeRepository->myCommandeByCom($id)[0]['c_adLiv'],
            'facId' => $facId,
            'comDate' => $comDate,
            'facDate' => $facDate,
            'commandes' => $commandeRepository->myCommandeByCom($id),
            'totals' => $commandeRepository->totalPrixCom($id)
        ]);
    }

    #[Route('/new', name: 'app_commande_crud_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commande = new Commande();
        $form = $this->createForm(Commande1Type::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($commande);
            $entityManager->flush();

            return $this->redirectToRoute('app_commande_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commande_crud/new.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_crud_show', methods: ['GET'])]
    public function show(Commande $commande, CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande_crud/show.html.twig', [
            'commande' => $commande,
            'commandes' => $commandeRepository->myCommande()
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commande_crud_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commande $commande, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Commande1Type::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_commande_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commande_crud/edit.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commande_crud_delete', methods: ['POST'])]
    public function delete(Request $request, Commande $commande, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commande->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commande);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commande_crud_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commande_crud/_delete_form.html.twig
<form method="post" action="{{ path('app_commande_crud_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commande_crud/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commande_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commande{% endblock %}

{% block body %}
    <h1>Edit Commande</h1>

    {{ include('commande_crud/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_commande_crud_index') }}">back to list</a>

    {{ include('commande_crud/_delete_form.html.twig') }}
{% endblock %}

templates/commande_crud/facture.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    {# <h1>Detail de ma commande</h1> #}
    <div class='container'>
        <div class='row'>    
            <img src="/images/logoFacture.jpg" class="logo col-6"> 
                <div class='col-6 my-auto'>
                    <div>Facture N° {{ facId }}</div>
                     <div>(Commande N°  {{ comId }}  du  {{ comDate ? comDate|date('Y-m-d') : '' }})</div>
                      <div>Date : {{ facDate ? facDate|date('Y-m-d') : '' }}</div>
                      
                </div>
            <div class='border mb-2 py-2'>
            Client : n°{{ utiId }}, {{ adresse }} , {{ tel }}, {{ email }}
            </div>
            <div class='border py-3'>
            Adresse de facturation : {{ adresseFac }}
            </div>
        </div>
    
    <div class='mt-5'> Description de la commande </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>REF.</th>
                <th>DESIGNATION</th>
                <th>P U</th>
                <th>Quantité</th>
                <th>Total HT</th>
                <th>TVA</th>
                <th>Total TTC</th>
                 {# <th>Adresse</th>
                <th>Adresse de facturation</th>
                <th>Numero client</th>
                <th>Email</th>
                <th>Telephone</th>
                <th>Date commande</th> #}
               {#  <th>Com_adresse_facturation</th>
                <th>Com_isPaid</th>
                <th>Com_moyen_paiement</th>
                <th>Com_stripe_session_id</th>
                <th>Com_paypal_id</th>
                <th>actions</th> #}
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
             <td>{{ commande.p_id }}</td>
              <td>{{ commande.p_nom }}</td>
                <td>{{ commande.p_prix| format_currency('EUR', locale='fr') }}</td>
                <td>{{ commande.p_quantite }}</td>
                <td>{{ commande.p_SousTotal| format_currency('EUR', locale='fr') }}</td>
                <td>{{ (commande.p_SousTotal * 0.2)| format_currency('EUR', locale='fr')}}</td>
                <td>{{(commande.p_SousTotal + (commande.p_SousTotal * 0.2))| format_currency('EUR', locale='fr')}}</td>
                {# <td>{{ commande.c_adLiv }}</td>
                <td>{{ commande.c_adFac }}</td>
                <td>{{ commande.user_id }}</td>
                <td>{{ commande.user_email }}</td>
                <td>{{ commande.user_tel }}</td>
                 <td>{{ commande.c_date ? commande.c_date|date('Y-m-d') : '' }}</td> #}
                  {# <td>{{ commande.c_date ? commande.c_date|date('Y-m-d H:i:s') : '' }}</td> #}
                {# <td>{{ commande.p_SousTotal }}</td> #}
                {# <td>{{ commande.comAdresseFacturation }}</td>
                <td>{{ commande.comIsPaid ? 'Yes' : 'No' }}</td>
                <td>{{ commande.comMoyenPaiement }}</td>
                <td>{{ commande.comStripeSessionId }}</td>
                <td>{{ commande.comPaypalId }}</td> #}
                {# <td>      #}
                {# <a href="{{ path('app_commande_crud_show', {'id': commande.id}) }}">show</a> #}
                    {# <a href="{{ path('app_commande_crud_edit', {'id': commande.id}) }}">edit</a> #}
                {# </td> #}
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
           {% for total in totals %}
           <td>Transporteur</td>
           <td>{{ total.p_tra }} </td>
           <td> {{ total.p_fdp | format_currency('EUR', locale='fr') }} </td>
           <td> </td>
            <td> {{ total.p_fdp | format_currency('EUR', locale='fr')}} </td>
             <td colspan="2"></td>
                          {% endfor %}
        </tbody>
          <tfoot>
          {% for total in totals %}
                        <tr>
                         <td colspan="2"></td>
                            <td colspan="2">Total</td>
                            
                            <td> {{ total.p_total | format_currency('EUR', locale='fr')}} </td>
                            <td> {{ ((total.p_total - total.p_fdp)  * 0.2) | format_currency('EUR', locale='fr') }} </td>
                            <td> {{ (((total.p_total - total.p_fdp)  * 0.2) + (total.p_total))| format_currency('EUR', locale='fr') }} </td>
                        </tr>
                          {% endfor %}
          </tfoot>
    </table>

    {# <a href="{{ path('app_commande_crud_new') }}">Create new</a> #}
    <p>Solde payable sous « délai de paiement » à réception de facture, par « mode de paiement ».</p>
    <div>Pénalité de retard au taux annuel de « nombre » % </div>
<div>En cas de retard de paiement, application d’une indemnité forfaitaire pour frais de recouvrement de 40 euros (article D. 441-5 du code du commerce).</div>
   <div class='mt-5'> FilRougeCompany </div>
    <div> SA au capital de  </div>
    </div>

    
{% endblock %}

templates/commande_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Com_date</th>
                <th>Com_commentaire</th>
                <th>Com_adresse_livraison</th>
                <th>Com_adresse_facturation</th>
                <th>Com_isPaid</th>
                <th>Com_moyen_paiement</th>
                <th>Com_stripe_session_id</th>
                <th>Com_paypal_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.comDate ? commande.comDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.comCommentaire }}</td>
                <td>{{ commande.comAdresseLivraison }}</td>
                <td>{{ commande.comAdresseFacturation }}</td>
                <td>{{ commande.comIsPaid ? 'Yes' : 'No' }}</td>
                <td>{{ commande.comMoyenPaiement }}</td>
                <td>{{ commande.comStripeSessionId }}</td>
                <td>{{ commande.comPaypalId }}</td>
                <td>
                    <a href="{{ path('app_commande_crud_show', {'id': commande.id}) }}">show</a>
                    <a href="{{ path('app_commande_crud_edit', {'id': commande.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commande_crud_new') }}">Create new</a>
{% endblock %}

templates/commande_crud/my_commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Com_date</th>
                <th>Com_commentaire</th>
                <th>Com_adresse_livraison</th>
                <th>Com_adresse_facturation</th>
                <th>Com_isPaid</th>
                <th>Com_moyen_paiement</th>
                <th>Com_stripe_session_id</th>
                <th>Com_paypal_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
              <td>{{ commande.id }}</td>
                <td>{{ commande.comDate ? commande.comDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.comCommentaire }}</td>
                <td>{{ commande.comAdresseLivraison }}</td>
                <td>{{ commande.comAdresseFacturation }}</td>
                <td>{{ commande.comIsPaid ? 'Yes' : 'No' }}</td>
                <td>{{ commande.comMoyenPaiement }}</td>
                <td>{{ commande.comStripeSessionId }}</td>
                <td>{{ commande.comPaypalId }}</td>
                <td>     
                <a href="{{ path('app_my_commande_crud_show', {'id': commande.id}) }}">show</a>
                {# <a href="{{ path('app_my_commande_crud_show',{'id':  app.user.id  }) }}>show</a> #}
                    {# <a href="{{ path('app_commande_crud_edit', {'id': commande.id}) }}">edit</a> #}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_commande_crud_new') }}">Create new</a> #}
{% endblock %}

templates/commande_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block body %}
    <h1>Create new Commande</h1>

    {{ include('commande_crud/_form.html.twig') }}

    <a href="{{ path('app_commande_crud_index') }}">back to list</a>
{% endblock %}

templates/commande_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>Com_date</th>
                <td>{{ commande.comDate ? commande.comDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Com_commentaire</th>
                <td>{{ commande.comCommentaire }}</td>
            </tr>
            <tr>
                <th>Com_adresse_livraison</th>
                <td>{{ commande.comAdresseLivraison }}</td>
            </tr>
            <tr>
                <th>Com_adresse_facturation</th>
                <td>{{ commande.comAdresseFacturation }}</td>
            </tr>
            <tr>
                <th>Com_isPaid</th>
                <td>{{ commande.comIsPaid ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Com_moyen_paiement</th>
                <td>{{ commande.comMoyenPaiement }}</td>
            </tr>
            <tr>
                <th>Com_stripe_session_id</th>
                <td>{{ commande.comStripeSessionId }}</td>
            </tr>
            <tr>
                <th>Com_paypal_id</th>
                <td>{{ commande.comPaypalId }}</td>
            </tr>
        </tbody>
         {% for commande in commandes %}
          <tr>
          <td>{{ commande.p_nom }}</td>
                <td>{{ commande.p_prix }}</td>
                <td>{{ commande.p_quantite }}</td>
                </tr>
                  {% endfor %}
    </table>

    <a href="{{ path('app_commande_crud_index') }}">back to list</a>

    <a href="{{ path('app_commande_crud_edit', {'id': commande.id}) }}">edit</a>

    {{ include('commande_crud/_delete_form.html.twig') }}
{% endblock %}